### PR TITLE
Release 3.0.2

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
[intbitset 3.0.2](https://pypi.org/project/intbitset/3.0.2/) was released manually from https://github.com/nexB/intbitset by @pombredanne as we needed this for enabling and testing for python3.11 support.

### CODE REVIEW

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra do you mind to rebase on the latest?

**Comment by pombredanne** [comment]
actually this has been merged?

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne see https://github.com/nexB/intbitset/pull/3 this was merged and is released at https://pypi.org/project/intbitset/3.0.2/ from https://github.com/nexB/intbitset

**Comment by pombredanne** [comment]
All merged... closing!

**Pull request closed without merging**
